# Generated by Django 2.1.7 on 2019-02-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='itemno',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturerCode',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
